### ISSUE TITLE
fx-CG50 compatibility

### ISSUE THREAD

**Issue by critor** [balping/othello-prizm#1]
Looks very nice but unfortunately it doesn't work on my fx-CG50.

The graphics are missing, here's a screen capture :
![image](https://user-images.githubusercontent.com/5098064/39398854-82b280c4-4b14-11e8-9d21-2fd7cf7fc308.png)

I think the VRAM address did change, so you'd just need to get it through a syscall which would work in all cases, instead of hard-coding it.

Best regards.

**Comment by balping** [comment]
These addresses are defined in the SDK, so maybe if you can obtain an sdk version targeted to cg50, you might be able to compile it.

**Comment by balping** [comment]
Resolved in https://github.com/balping/othello-prizm/commit/654cb07492b4bf683593d197bc003cac31abf59f. You can download v1.01
